


cloud:
  aws:
    region:
      auto: false
      static: us-east-1
      use-default-aws-region-chain: true
    stack: false
    stack.auto: false
    credentials:
      access-key: AKIA2WL7QKJOQJGIXXH4
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error